name: image_to_pdf_scanner
description: Image to PDF Converter & Document Scanner with Unity Ads
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  pdf: ^3.10.8
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  edge_detection: ^1.1.5
  unity_ads_plugin: ^0.3.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
